import Head from 'next/head'


export default function Home() {

  return (
    <div className="teste2">
      <Head>
        <title>DailyMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>HomePage</h1>
      </div>
    </div>
  )
}

