import Link from 'next/link'
import Head from 'next/head'

export default function Home() {

  return (
    <>
      <Head>
        <title>Música do dia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <meta lang="pt-BR" />
      </Head>

      <div className="page-full">
        <div className="header-navbar">
          <p>Músicas mais ouvidas</p>
          <p>Playlista da semana</p>
        </div>

        <div className="dm-poster__container">
          <div className="dm-poster-main">
            <h4>Música do dia</h4>
            <Link href="/musica-hoje">
              <a>Conferir</a>
            </Link>
          </div>
        </div>

        <footer className="home-footer">
          <p>Powered by: <a href="intagram/matheusvancoll" target="_blank">Matheus Vancoll</a></p>
        </footer>
      </div>

    </>
  )
}

