import Head from 'next/head'

import CardMusic from '../components/CardMusic'

export default function Teste() {
  return (
    <div>
      <Head>
        <title>DailyMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CardMusic />
    
    </div>
  )
}