import useSWR from 'swr'
import Link from 'next/link'

import Head from 'next/head'
import CardMusic from '../components/CardMusic'
import Navbar from '../components/Navbar'

import getRoutersJson from '../utils/axios-api'

export default function Teste() {

  const { data, error } = useSWR('/api/mongodb-api/get-today-music', getRoutersJson)

  if (error) return (
    RenderPage("Ops, não conseguimos carregar as informações")
  )

  if (!data) return (
    RenderPage("loading...")
  )

  if(!data.data.music) return (
    RenderPage("Não deu bom")
  )

  if (data) return (
    RenderPage("", data.data.music )
  )
  
  function RenderPage(stateRequest, infoMusic){
    return(
      <>
      <Head>
        <title>Música do dia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <meta lang="pt-BR" />
      </Head>

      <div className="page-full rotated">
        <Navbar />

        <div className="dm-poster__container">
          {stateRequest ? stateRequest : <CardMusic music={(data.data.music)}/>}
        </div>
        
        <footer className="home-footer">
          <p>Powered by: <a href="https://www.instagram.com/matheusvancoll/" target="_blank" rel="noreferrer">Matheus Vancoll</a></p>
        </footer>
      </div>
    </>
    )
  }
}