import Head from 'next/head'
import { useState } from 'react'
import Navbar from '../components/Navbar'

import getRoutersJson from '../utils/axios-api'

export default function Teste() {

  const [Musichint, setMusicHint] = useState("")
  
  return (
    <>
      <Head>
        <title>Música do dia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <meta lang="pt-BR" />
      </Head>

      <div className="page-full rotated">
        <Navbar />

        <div className="dm-poster__container">
          <h3>Envie sua sugestão de música</h3>
          <form className="form-music-hint" action="./api/mongodb-api/insert-music-hint" method="POST">
            <input 
              type="text" 
              name="musicHint"
              placeholder="Nome da Música ex: Justin Bieber - One Time"
              onChange={ e => setMusicHint(e.target.value)} />
            <button type="submit">Enviar sugestão</button>
          </form>
        </div>
        <footer className="home-footer">
          <p>Powered by: <a href="https://www.instagram.com/matheusvancoll/" target="_blank" rel="noreferrer">Matheus Vancoll</a></p>
        </footer>
      </div>
    </>
  )
}